### ISSUE TITLE
Fix convention for tensor shapes

### ISSUE THREAD

**Issue by wazizian** [mlelarge/graph_neural_net#2]
Hi!
I am modifying the code so the same convention for the shape of tensors is used everywhere (see PR).
But I'm not sure we have chosen the right one.
You and we have chosen` (bs, n_vertices, n_vertices, features) `but Marron preferred `(bs, features, n_vertices, n_vertices)`. Indeed the later matches Pytorch's convention for images and so makes convolutions natural.
In one case, MLPs and blocks have to be adapted and in the other, it is the data generation process, so it is a similar amount of work.
What do you think ?
Bests,
Waïss

**Comment by mlelarge** [comment]
Indeed! `(bs,n_vertices,n_vertices,features)` is more graph-friendly but requires a permutation before applying `conv2d`. Since dataloaders use this convention just keep it...
